let message = document.getElementById("message");

let messageOnline = () => {
  message.textContent = "Internet Connection Available";
  message.style.cssText = "background-color: #e7f6d5; color: #689f38";
};
let messageOffline = () => {
  message.textContent = "No Internet Connection";
  message.style.cssText = "background-color: #ffdde0; color: #d32f2f";
};

if (window.navigator.onLine) {
  messageOnline();
} else {
  messageOffline();
}

window.addEventListener("online", messageOnline);
window.addEventListener("offline", messageOffline);
/*kZeKAlGJ1dCBub3QgdGhlIFJhdmVuc2hhZGUgc2hlIGtuZXcuIFRoZSBzdHJlZ
XRzIHdlcmUgYnJpZ2h0ZXIsIGJ1c3RsaW5nIHdpdGggaG9yc2UtZHJhd24gY2FycmlhZ2VzLCBwZW9wbGUgZHJlc3NlZCBpbiBlbGV
nYW50IFZpY3RvcmlhbiBhdHRpcmUsIGFuZCBzdHJhbmdlIGRldmljZXMgc2hlIGhhZCBuZXZlciBzZWVuIGJlZm9yZS4gSXQgd2FzI
HRoZSBwYXN0LgoKUGFuaWNrZWQsIHNoZSBjbHV0Y2hlZCB0aGUgcG9ja2V0IHdhdGNoIHRpZ2h0bHksIHJlYWxpemluZyBpdCB3YXM
gdGhlIGtleSB0byBoZXIgam91bmV5LiBTaGUgZGFzaGVkIHRocm91Z2ggdGhlIHN0cmVldHMsIG1hcnZlbGluZyBhdCBob3cgZGlmZ
mVyZW50IGV2ZXJ5dGhpbmcgd2FzLiBGaW5hbGx5LCBzaGUgZm91bmQgdGhlIHlvdW5nZXIgdmVyc2lvbiBvZiBNci4gQWxyaWMsIHd
vcmtpbmcgb24gY2xvY2tzIHdpdGggdGhlIHNhbWUgY2FyZSBhbmQgcHJlY2lzaW9uLgoKIllvdeKAmXZlIGNvbWUgdGhyb3VnaCB0a
W1lLCIgaGUgc2FpZCBjYWxtbHksFlagFces{IGFzIG}IHNoZSBjbHV0Y2hlZCB0aGUgcG9ja2V0IHdhdGNoIHRpZ2h0bHksIHJlYWxpemluZyBpdCB3YXM
gdGhlIGtleSB0byBoZXIgam91bmV5LiBTaGUgZGFzaGVkIHRocm91Z2ggdGhlIHN0cmVldHMsIG1hcnZlbGluZyBhdCBob3cgZGlmZ
mVyZW50IGV2ZXJ5dGhpbmcgd2FzLiBGaW5hbGx5LCBzaGUgZm91bmQgdGhlIHlvdW5nZXIgdmVyc2lvbiBvZiBNci4gQWxyaWMsIHd
vcmtpbmcgb24gY2xvY2tzIHdpdGggdIHNoZSBjbHV0Y2hlZCB0aGUgcG9ja2V0IHdhdGNoIHRpZ2h0bHksIHJlYWxpemluZyBpdCB3YXM
gdGhlIGtleSB0byBoZXIgam91bmV5LiBTaGUgZGFzaGVkIHRocm91Z2ggdGhlIHN0cmVldHMsIG1hcnZlbGluZyBhdCBob3cgZGlmZ
mVyZW50IGV2ZXJ5dGhpbmcgd2FzLiBGaW5hbGx5LCBzaGUgZm91bmQgdGhlIHlvdW5nZXIgdmVyc2lvbiBvZiBNci4gQWxyaWMsIHd
vcmtpbmcgb24gY2xvY2tzIHdpdGggdNrZWQsIHNoZSBjbHV0Y2hlZCB0aGUgcG9ja2V0IHdhdGNoIHRpZ2h0bHksIHJlYWxpemluZyBpdCB3YXM
gdGhlIGtleSB0byBoZXIgam91bmV5LiBTaGUgZGFzaGVkIHRocm91Z2ggdGhlIHN0cmVldHMsIG1hcnZlbGluZyBhdCBob3cgZGlmZ
mVyZW50IGV2ZXJ5dGhpbmcgd2FzLiBGaW5hbGx5LCBzaGUgZm91bmQgdGhlIHlvdW5nZXIgdmVyc2lvbiBvZiBNci4gQWxyaWMsIHd
vcmtpbmcgb24gY2xvY2tzIHdpdGggdGhlIHNhbWUgY2FyZSBhbmQgcHJlY2lzaW9uLgoKIllvdeKAmXZlIGNvbWUgdGhyb3VnaCB0a
W1lLCIgaGUgc2FpZCBj
*/